# Generated by Django 4.2.29 on 2026-03-23 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='jobs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scoring_mode', models.CharField(choices=[('auto', 'Auto'), ('llm', 'LLM'), ('deterministic', 'Deterministic')], default='auto', max_length=20)),
                ('total_resumes', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='matcherapp.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('raw_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='matcherapp.matchrun')),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('final_score', models.FloatField(default=0.0)),
                ('confidence', models.CharField(default='MEDIUM', max_length=10)),
                ('recommendation', models.CharField(default='NO_MATCH', max_length=20)),
                ('d1_skills', models.FloatField(default=0.0)),
                ('d2_seniority', models.FloatField(default=0.0)),
                ('d3_domain', models.FloatField(default=0.0)),
                ('d4_constraints', models.FloatField(default=0.0)),
                ('dim_composite', models.FloatField(default=0.0)),
                ('ce_sigmoid', models.FloatField(default=0.0)),
                ('ce_weight_used', models.FloatField(default=0.0)),
                ('scoring_mode', models.CharField(default='auto', max_length=20)),
                ('strengths', models.JSONField(default=list)),
                ('gaps', models.JSONField(default=list)),
                ('rationale', models.TextField(blank=True)),
                ('skill_detail', models.JSONField(default=dict)),
                ('seniority_detail', models.JSONField(default=dict)),
                ('domain_detail', models.JSONField(default=dict)),
                ('constraint_detail', models.JSONField(default=dict)),
                ('stage_scores', models.JSONField(default=dict)),
                ('threat_level', models.CharField(default='NONE', max_length=20)),
                ('adversarial_penalty', models.FloatField(default=0.0)),
                ('threat_flags', models.JSONField(default=list)),
                ('match_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='matcherapp.matchrun')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcherapp.resume')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
